# Site settings
title: Tan Chun Hoong Clement
# twitter_username: rob_hinds
name: Tan Chun Hoong Clement

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/tanchc
   
#Any buzzword skills you want to include
skills:
 - Python
 - CSharp
 - Java
 - C

#Work experience is required
roles:
 - title: Software Engineer
   start: 2017
   end: 2018
   employer: Markedshot
   description: Markedshot is a Singapore-based start-up that crowdsources photographs from over 150,000 photographers around the world. Markedshot also rewards fans for creating good content, holds User-Generated Content Campaigns and optionally let voters pick the winners for the campaign.

#Education is required
education:
 - level: Bachelor of Engineering (B.Eng.)
   date: 2016 - 2020
   subject: Computer Engineering
   school: National University of Singapore
 - level: GCE A Level
   date: 2012 - 2013
   school: Meridian Junior College

#List of interesting Github repo/projects to include - optional
github:
 - tanchc/contacthub
 - tanchc/PSA_YiWanKuai

gitlab:
 - robocodez/robowarriors

itch.io:
 - jam/gamecraft2016/rate/101696


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Mobile Application Development</strong>: I am experienced in a variety of Android API’s. I have recently interned at Markedshot, a Singapore-based start-up that crowdsources photographs, which relied on Android Studios as their main development tool to manage their mobile application for Android phones in addition to others. I also have exprience in the use of . <br/><br/>
   <strong>Web Development</strong>: Some experience in HTML5, CSS and Javascript. Also worked with Bootstrap framework before.<br/><br/>
   <strong>Game Development</strong>: Experienced in using Unity as a game development tools. <br/><br/>
